/**
 * Curated Unicode emoji catalog for composer insert + reactions.
 * Pattern matches Slack/WhatsApp: categories + searchable names/keywords.
 * (No custom packs / skin-tone picker in v1.)
 */

export type EmojiCategoryId =
  | "smileys"
  | "gestures"
  | "hearts"
  | "animals"
  | "food"
  | "travel"
  | "activities"
  | "objects"
  | "symbols"

export type EmojiItem = {
  emoji: string
  /** Primary search label */
  name: string
  keywords?: string[]
}

export type EmojiCategory = {
  id: EmojiCategoryId
  label: string
  /** Category tab glyph */
  icon: string
  items: EmojiItem[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "😀",
    items: [
      { emoji: "😀", name: "grinning", keywords: ["happy", "smile"] },
      { emoji: "😃", name: "smiley", keywords: ["happy", "joy"] },
      { emoji: "😄", name: "smile", keywords: ["happy", "laugh"] },
      { emoji: "😁", name: "grin", keywords: ["happy"] },
      { emoji: "😆", name: "laughing", keywords: ["lol", "haha"] },
      { emoji: "😅", name: "sweat smile", keywords: ["relief"] },
      { emoji: "🤣", name: "rofl", keywords: ["lol", "laugh"] },
      { emoji: "😂", name: "joy", keywords: ["tears", "laugh", "lol"] },
      { emoji: "🙂", name: "slightly smiling", keywords: ["smile"] },
      { emoji: "🙃", name: "upside down", keywords: ["silly"] },
      { emoji: "😉", name: "wink", keywords: ["flirt"] },
      { emoji: "😊", name: "blush", keywords: ["happy", "smile"] },
      { emoji: "😇", name: "innocent", keywords: ["angel"] },
      { emoji: "🥰", name: "smiling hearts", keywords: ["love"] },
      { emoji: "😍", name: "heart eyes", keywords: ["love", "crush"] },
      { emoji: "🤩", name: "star struck", keywords: ["wow"] },
      { emoji: "😘", name: "kiss", keywords: ["love"] },
      { emoji: "😗", name: "kissing", keywords: ["love"] },
      { emoji: "😚", name: "kissing closed eyes", keywords: ["love"] },
      { emoji: "😙", name: "kissing smiling", keywords: ["love"] },
      { emoji: "🥲", name: "smiling tear", keywords: ["touched"] },
      { emoji: "😋", name: "yum", keywords: ["delicious", "tongue"] },
      { emoji: "😛", name: "tongue", keywords: ["silly"] },
      { emoji: "😜", name: "wink tongue", keywords: ["silly"] },
      { emoji: "🤪", name: "zany", keywords: ["crazy", "goofy"] },
      { emoji: "😝", name: "squinting tongue", keywords: ["silly"] },
      { emoji: "🤑", name: "money mouth", keywords: ["rich"] },
      { emoji: "🤗", name: "hugging", keywords: ["hug"] },
      { emoji: "🤭", name: "hand over mouth", keywords: ["oops", "secret"] },
      { emoji: "🤫", name: "shushing", keywords: ["quiet", "secret"] },
      { emoji: "🤔", name: "thinking", keywords: ["hmm", "consider"] },
      { emoji: "🤐", name: "zipper mouth", keywords: ["quiet", "secret"] },
      { emoji: "🤨", name: "raised eyebrow", keywords: ["skeptical"] },
      { emoji: "😐", name: "neutral", keywords: ["meh"] },
      { emoji: "😑", name: "expressionless", keywords: ["blank"] },
      { emoji: "😶", name: "no mouth", keywords: ["silent"] },
      { emoji: "😏", name: "smirk", keywords: ["smug"] },
      { emoji: "😒", name: "unamused", keywords: ["meh", "annoyed"] },
      { emoji: "🙄", name: "eye roll", keywords: ["whatever"] },
      { emoji: "😬", name: "grimacing", keywords: ["awkward"] },
      { emoji: "😮‍💨", name: "exhale", keywords: ["relief", "sigh"] },
      { emoji: "🤥", name: "lying", keywords: ["pinocchio"] },
      { emoji: "😌", name: "relieved", keywords: ["calm"] },
      { emoji: "😔", name: "pensive", keywords: ["sad"] },
      { emoji: "😪", name: "sleepy", keywords: ["tired"] },
      { emoji: "🤤", name: "drooling", keywords: ["want"] },
      { emoji: "😴", name: "sleeping", keywords: ["zzz", "tired"] },
      { emoji: "😷", name: "mask", keywords: ["sick"] },
      { emoji: "🤒", name: "thermometer", keywords: ["sick", "fever"] },
      { emoji: "🤕", name: "head bandage", keywords: ["hurt", "injured"] },
      { emoji: "🤢", name: "nauseated", keywords: ["sick"] },
      { emoji: "🤮", name: "vomiting", keywords: ["sick"] },
      { emoji: "🥵", name: "hot face", keywords: ["heat"] },
      { emoji: "🥶", name: "cold face", keywords: ["freeze"] },
      { emoji: "🥴", name: "woozy", keywords: ["dizzy"] },
      { emoji: "😵", name: "dizzy", keywords: ["dead"] },
      { emoji: "🤯", name: "exploding head", keywords: ["mind blown", "shock"] },
      { emoji: "🤠", name: "cowboy", keywords: ["hat"] },
      { emoji: "🥳", name: "party face", keywords: ["celebrate", "birthday"] },
      { emoji: "🥸", name: "disguise", keywords: ["glasses"] },
      { emoji: "😎", name: "sunglasses", keywords: ["cool"] },
      { emoji: "🤓", name: "nerd", keywords: ["glasses"] },
      { emoji: "🧐", name: "monocle", keywords: ["inspect"] },
      { emoji: "😕", name: "confused", keywords: ["huh"] },
      { emoji: "😟", name: "worried", keywords: ["concern"] },
      { emoji: "🙁", name: "slightly frowning", keywords: ["sad"] },
      { emoji: "☹️", name: "frowning", keywords: ["sad"] },
      { emoji: "😮", name: "open mouth", keywords: ["wow", "surprised"] },
      { emoji: "😯", name: "hushed", keywords: ["surprise"] },
      { emoji: "😲", name: "astonished", keywords: ["shock"] },
      { emoji: "😳", name: "flushed", keywords: ["embarrassed"] },
      { emoji: "🥺", name: "pleading", keywords: ["puppy", "please"] },
      { emoji: "😦", name: "frowning open", keywords: ["shock"] },
      { emoji: "😧", name: "anguished", keywords: ["worried"] },
      { emoji: "😨", name: "fearful", keywords: ["scared"] },
      { emoji: "😰", name: "anxious", keywords: ["sweat", "nervous"] },
      { emoji: "😥", name: "sad relieved", keywords: ["disappointed"] },
      { emoji: "😢", name: "cry", keywords: ["tear", "sad"] },
      { emoji: "😭", name: "sob", keywords: ["cry", "sad"] },
      { emoji: "😱", name: "scream", keywords: ["fear", "shock"] },
      { emoji: "😖", name: "confounded", keywords: ["frustrated"] },
      { emoji: "😣", name: "persevering", keywords: ["struggle"] },
      { emoji: "😞", name: "disappointed", keywords: ["sad"] },
      { emoji: "😓", name: "downcast", keywords: ["sweat"] },
      { emoji: "😩", name: "weary", keywords: ["tired"] },
      { emoji: "😫", name: "tired", keywords: ["exhausted"] },
      { emoji: "🥱", name: "yawning", keywords: ["bored", "sleepy"] },
      { emoji: "😤", name: "triumph", keywords: ["steam", "angry"] },
      { emoji: "😡", name: "pouting", keywords: ["angry", "mad"] },
      { emoji: "😠", name: "angry", keywords: ["mad"] },
      { emoji: "🤬", name: "cursing", keywords: ["angry", "swear"] },
      { emoji: "😈", name: "smiling devil", keywords: ["evil"] },
      { emoji: "👿", name: "angry devil", keywords: ["evil"] },
      { emoji: "💀", name: "skull", keywords: ["dead"] },
      { emoji: "☠️", name: "skull crossbones", keywords: ["danger"] },
      { emoji: "💩", name: "poop", keywords: ["poo"] },
      { emoji: "🤡", name: "clown", keywords: ["joke"] },
      { emoji: "👹", name: "ogre", keywords: ["monster"] },
      { emoji: "👺", name: "goblin", keywords: ["monster"] },
      { emoji: "👻", name: "ghost", keywords: ["halloween"] },
      { emoji: "👽", name: "alien", keywords: ["ufo"] },
      { emoji: "👾", name: "alien monster", keywords: ["game"] },
      { emoji: "🤖", name: "robot", keywords: ["bot"] },
      { emoji: "🎃", name: "jack o lantern", keywords: ["halloween"] },
      { emoji: "😺", name: "smiley cat", keywords: ["cat"] },
      { emoji: "😸", name: "grin cat", keywords: ["cat"] },
      { emoji: "😹", name: "joy cat", keywords: ["cat", "laugh"] },
      { emoji: "😻", name: "heart eyes cat", keywords: ["cat", "love"] },
      { emoji: "😼", name: "smirk cat", keywords: ["cat"] },
      { emoji: "😽", name: "kissing cat", keywords: ["cat"] },
      { emoji: "🙀", name: "scream cat", keywords: ["cat"] },
      { emoji: "😿", name: "crying cat", keywords: ["cat", "sad"] },
      { emoji: "😾", name: "pouting cat", keywords: ["cat", "angry"] },
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    icon: "👍",
    items: [
      { emoji: "👋", name: "wave", keywords: ["hello", "hi", "bye"] },
      { emoji: "🤚", name: "raised back hand", keywords: ["stop"] },
      { emoji: "🖐️", name: "hand splayed", keywords: ["five"] },
      { emoji: "✋", name: "raised hand", keywords: ["stop", "high five"] },
      { emoji: "🖖", name: "vulcan", keywords: ["spock"] },
      { emoji: "👌", name: "ok hand", keywords: ["okay", "perfect"] },
      { emoji: "🤌", name: "pinched fingers", keywords: ["italian"] },
      { emoji: "🤏", name: "pinching", keywords: ["small"] },
      { emoji: "✌️", name: "victory", keywords: ["peace"] },
      { emoji: "🤞", name: "crossed fingers", keywords: ["luck"] },
      { emoji: "🤟", name: "love you gesture", keywords: ["ily"] },
      { emoji: "🤘", name: "horns", keywords: ["rock"] },
      { emoji: "🤙", name: "call me", keywords: ["shaka"] },
      { emoji: "👈", name: "point left", keywords: ["left"] },
      { emoji: "👉", name: "point right", keywords: ["right"] },
      { emoji: "👆", name: "point up", keywords: ["up"] },
      { emoji: "👇", name: "point down", keywords: ["down"] },
      { emoji: "☝️", name: "index up", keywords: ["one"] },
      { emoji: "👍", name: "thumbs up", keywords: ["yes", "like", "+1"] },
      { emoji: "👎", name: "thumbs down", keywords: ["no", "dislike", "-1"] },
      { emoji: "✊", name: "fist", keywords: ["power"] },
      { emoji: "👊", name: "punch", keywords: ["fistbump"] },
      { emoji: "🤛", name: "left fist", keywords: ["bump"] },
      { emoji: "🤜", name: "right fist", keywords: ["bump"] },
      { emoji: "👏", name: "clap", keywords: ["applause", "bravo"] },
      { emoji: "🙌", name: "raising hands", keywords: ["celebrate", "hooray"] },
      { emoji: "👐", name: "open hands", keywords: ["hug"] },
      { emoji: "🤲", name: "palms up", keywords: ["pray", "receive"] },
      { emoji: "🤝", name: "handshake", keywords: ["deal", "agree"] },
      { emoji: "🙏", name: "folded hands", keywords: ["please", "thanks", "pray"] },
      { emoji: "✍️", name: "writing hand", keywords: ["write"] },
      { emoji: "💅", name: "nail polish", keywords: ["nails"] },
      { emoji: "🤳", name: "selfie", keywords: ["phone"] },
      { emoji: "💪", name: "muscle", keywords: ["strong", "flex"] },
      { emoji: "🦾", name: "mechanical arm", keywords: ["prosthetic"] },
      { emoji: "🦵", name: "leg", keywords: ["kick"] },
      { emoji: "🦶", name: "foot", keywords: ["kick"] },
      { emoji: "👂", name: "ear", keywords: ["listen"] },
      { emoji: "👃", name: "nose", keywords: ["smell"] },
      { emoji: "🧠", name: "brain", keywords: ["smart"] },
      { emoji: "👀", name: "eyes", keywords: ["look", "see", "watching"] },
      { emoji: "👁️", name: "eye", keywords: ["see"] },
      { emoji: "👅", name: "tongue", keywords: ["taste"] },
      { emoji: "👄", name: "mouth", keywords: ["lips"] },
      { emoji: "💋", name: "kiss mark", keywords: ["lips", "love"] },
      { emoji: "🩸", name: "drop of blood", keywords: ["blood"] },
    ],
  },
  {
    id: "hearts",
    label: "Hearts",
    icon: "❤️",
    items: [
      { emoji: "❤️", name: "red heart", keywords: ["love", "like"] },
      { emoji: "🧡", name: "orange heart", keywords: ["love"] },
      { emoji: "💛", name: "yellow heart", keywords: ["love"] },
      { emoji: "💚", name: "green heart", keywords: ["love"] },
      { emoji: "💙", name: "blue heart", keywords: ["love"] },
      { emoji: "💜", name: "purple heart", keywords: ["love"] },
      { emoji: "🖤", name: "black heart", keywords: ["love"] },
      { emoji: "🤍", name: "white heart", keywords: ["love"] },
      { emoji: "🤎", name: "brown heart", keywords: ["love"] },
      { emoji: "💔", name: "broken heart", keywords: ["sad", "heartbreak"] },
      { emoji: "❣️", name: "heart exclamation", keywords: ["love"] },
      { emoji: "💕", name: "two hearts", keywords: ["love"] },
      { emoji: "💞", name: "revolving hearts", keywords: ["love"] },
      { emoji: "💓", name: "beating heart", keywords: ["love"] },
      { emoji: "💗", name: "growing heart", keywords: ["love"] },
      { emoji: "💖", name: "sparkling heart", keywords: ["love"] },
      { emoji: "💘", name: "cupid", keywords: ["love", "arrow"] },
      { emoji: "💝", name: "gift heart", keywords: ["love", "present"] },
      { emoji: "💟", name: "heart decoration", keywords: ["love"] },
      { emoji: "☮️", name: "peace", keywords: ["peace"] },
      { emoji: "✝️", name: "cross", keywords: ["christian"] },
      { emoji: "☪️", name: "star and crescent", keywords: ["islam"] },
      { emoji: "🕉️", name: "om", keywords: ["hindu"] },
      { emoji: "✡️", name: "star of david", keywords: ["jewish"] },
      { emoji: "🔯", name: "dotted six-pointed star", keywords: ["star"] },
      { emoji: "☯️", name: "yin yang", keywords: ["balance"] },
      { emoji: "☸️", name: "wheel of dharma", keywords: ["buddhist"] },
      { emoji: "⚛️", name: "atom", keywords: ["science"] },
    ],
  },
  {
    id: "animals",
    label: "Nature",
    icon: "🌿",
    items: [
      { emoji: "🐶", name: "dog", keywords: ["puppy", "pet"] },
      { emoji: "🐱", name: "cat", keywords: ["kitten", "pet"] },
      { emoji: "🐭", name: "mouse", keywords: ["rodent"] },
      { emoji: "🐹", name: "hamster", keywords: ["pet"] },
      { emoji: "🐰", name: "rabbit", keywords: ["bunny"] },
      { emoji: "🦊", name: "fox", keywords: ["animal"] },
      { emoji: "🐻", name: "bear", keywords: ["animal"] },
      { emoji: "🐼", name: "panda", keywords: ["bear"] },
      { emoji: "🐨", name: "koala", keywords: ["animal"] },
      { emoji: "🐯", name: "tiger", keywords: ["animal"] },
      { emoji: "🦁", name: "lion", keywords: ["animal"] },
      { emoji: "🐮", name: "cow", keywords: ["animal"] },
      { emoji: "🐷", name: "pig", keywords: ["animal"] },
      { emoji: "🐸", name: "frog", keywords: ["animal"] },
      { emoji: "🐵", name: "monkey face", keywords: ["animal"] },
      { emoji: "🙈", name: "see no evil", keywords: ["monkey"] },
      { emoji: "🙉", name: "hear no evil", keywords: ["monkey"] },
      { emoji: "🙊", name: "speak no evil", keywords: ["monkey"] },
      { emoji: "🐒", name: "monkey", keywords: ["animal"] },
      { emoji: "🐔", name: "chicken", keywords: ["bird"] },
      { emoji: "🐧", name: "penguin", keywords: ["bird"] },
      { emoji: "🐦", name: "bird", keywords: ["animal"] },
      { emoji: "🐤", name: "baby chick", keywords: ["bird"] },
      { emoji: "🐣", name: "hatching chick", keywords: ["bird"] },
      { emoji: "🐥", name: "front chick", keywords: ["bird"] },
      { emoji: "🦆", name: "duck", keywords: ["bird"] },
      { emoji: "🦅", name: "eagle", keywords: ["bird"] },
      { emoji: "🦉", name: "owl", keywords: ["bird"] },
      { emoji: "🦇", name: "bat", keywords: ["halloween"] },
      { emoji: "🐺", name: "wolf", keywords: ["animal"] },
      { emoji: "🐗", name: "boar", keywords: ["animal"] },
      { emoji: "🐴", name: "horse", keywords: ["animal"] },
      { emoji: "🦄", name: "unicorn", keywords: ["magic"] },
      { emoji: "🐝", name: "bee", keywords: ["honey"] },
      { emoji: "🐛", name: "bug", keywords: ["insect"] },
      { emoji: "🦋", name: "butterfly", keywords: ["insect"] },
      { emoji: "🐌", name: "snail", keywords: ["slow"] },
      { emoji: "🐞", name: "ladybug", keywords: ["insect"] },
      { emoji: "🐜", name: "ant", keywords: ["insect"] },
      { emoji: "🦟", name: "mosquito", keywords: ["insect"] },
      { emoji: "🦗", name: "cricket", keywords: ["insect"] },
      { emoji: "🕷️", name: "spider", keywords: ["insect"] },
      { emoji: "🕸️", name: "web", keywords: ["spider"] },
      { emoji: "🐢", name: "turtle", keywords: ["slow"] },
      { emoji: "🐍", name: "snake", keywords: ["animal"] },
      { emoji: "🦎", name: "lizard", keywords: ["reptile"] },
      { emoji: "🦂", name: "scorpion", keywords: ["animal"] },
      { emoji: "🦀", name: "crab", keywords: ["seafood"] },
      { emoji: "🦞", name: "lobster", keywords: ["seafood"] },
      { emoji: "🦐", name: "shrimp", keywords: ["seafood"] },
      { emoji: "🐙", name: "octopus", keywords: ["sea"] },
      { emoji: "🦑", name: "squid", keywords: ["sea"] },
      { emoji: "🐠", name: "tropical fish", keywords: ["fish"] },
      { emoji: "🐟", name: "fish", keywords: ["sea"] },
      { emoji: "🐬", name: "dolphin", keywords: ["sea"] },
      { emoji: "🐳", name: "whale", keywords: ["sea"] },
      { emoji: "🐋", name: "whale", keywords: ["sea"] },
      { emoji: "🦈", name: "shark", keywords: ["sea"] },
      { emoji: "🐊", name: "crocodile", keywords: ["reptile"] },
      { emoji: "🐅", name: "tiger", keywords: ["animal"] },
      { emoji: "🐆", name: "leopard", keywords: ["animal"] },
      { emoji: "🦓", name: "zebra", keywords: ["animal"] },
      { emoji: "🦍", name: "gorilla", keywords: ["ape"] },
      { emoji: "🦧", name: "orangutan", keywords: ["ape"] },
      { emoji: "🐘", name: "elephant", keywords: ["animal"] },
      { emoji: "🦛", name: "hippo", keywords: ["animal"] },
      { emoji: "🦏", name: "rhino", keywords: ["animal"] },
      { emoji: "🐪", name: "camel", keywords: ["desert"] },
      { emoji: "🐫", name: "two hump camel", keywords: ["desert"] },
      { emoji: "🦒", name: "giraffe", keywords: ["animal"] },
      { emoji: "🦘", name: "kangaroo", keywords: ["animal"] },
      { emoji: "🦬", name: "bison", keywords: ["animal"] },
      { emoji: "🐃", name: "water buffalo", keywords: ["animal"] },
      { emoji: "🐂", name: "ox", keywords: ["animal"] },
      { emoji: "🐄", name: "cow", keywords: ["animal"] },
      { emoji: "🐎", name: "racehorse", keywords: ["animal"] },
      { emoji: "🐖", name: "pig", keywords: ["animal"] },
      { emoji: "🐏", name: "ram", keywords: ["sheep"] },
      { emoji: "🐑", name: "ewe", keywords: ["sheep"] },
      { emoji: "🦙", name: "llama", keywords: ["animal"] },
      { emoji: "🐐", name: "goat", keywords: ["animal"] },
      { emoji: "🦌", name: "deer", keywords: ["animal"] },
      { emoji: "🐕", name: "dog", keywords: ["pet"] },
      { emoji: "🐩", name: "poodle", keywords: ["dog"] },
      { emoji: "🦮", name: "guide dog", keywords: ["dog"] },
      { emoji: "🐈", name: "cat", keywords: ["pet"] },
      { emoji: "🐓", name: "rooster", keywords: ["chicken"] },
      { emoji: "🦃", name: "turkey", keywords: ["thanksgiving"] },
      { emoji: "🦚", name: "peacock", keywords: ["bird"] },
      { emoji: "🦜", name: "parrot", keywords: ["bird"] },
      { emoji: "🦢", name: "swan", keywords: ["bird"] },
      { emoji: "🦩", name: "flamingo", keywords: ["bird"] },
      { emoji: "🕊️", name: "dove", keywords: ["peace", "bird"] },
      { emoji: "🐇", name: "rabbit", keywords: ["bunny"] },
      { emoji: "🦝", name: "raccoon", keywords: ["animal"] },
      { emoji: "🦨", name: "skunk", keywords: ["animal"] },
      { emoji: "🦡", name: "badger", keywords: ["animal"] },
      { emoji: "🦫", name: "beaver", keywords: ["animal"] },
      { emoji: "🦦", name: "otter", keywords: ["animal"] },
      { emoji: "🦥", name: "sloth", keywords: ["slow"] },
      { emoji: "🐁", name: "mouse", keywords: ["rodent"] },
      { emoji: "🐀", name: "rat", keywords: ["rodent"] },
      { emoji: "🐿️", name: "chipmunk", keywords: ["animal"] },
      { emoji: "🦔", name: "hedgehog", keywords: ["animal"] },
      { emoji: "🐾", name: "paw prints", keywords: ["pet", "tracks"] },
      { emoji: "🐉", name: "dragon", keywords: ["myth"] },
      { emoji: "🐲", name: "dragon face", keywords: ["myth"] },
      { emoji: "🌵", name: "cactus", keywords: ["plant", "desert"] },
      { emoji: "🎄", name: "christmas tree", keywords: ["holiday"] },
      { emoji: "🌲", name: "evergreen", keywords: ["tree"] },
      { emoji: "🌳", name: "deciduous", keywords: ["tree"] },
      { emoji: "🌴", name: "palm", keywords: ["tree", "beach"] },
      { emoji: "🌱", name: "seedling", keywords: ["plant", "grow"] },
      { emoji: "🌿", name: "herb", keywords: ["leaf", "plant"] },
      { emoji: "☘️", name: "shamrock", keywords: ["luck"] },
      { emoji: "🍀", name: "four leaf clover", keywords: ["luck"] },
      { emoji: "🎍", name: "bamboo", keywords: ["plant"] },
      { emoji: "🎋", name: "tanabata", keywords: ["tree"] },
      { emoji: "🍃", name: "leaves", keywords: ["wind"] },
      { emoji: "🍂", name: "fallen leaf", keywords: ["autumn"] },
      { emoji: "🍁", name: "maple leaf", keywords: ["autumn", "canada"] },
      { emoji: "🍄", name: "mushroom", keywords: ["fungus"] },
      { emoji: "🌾", name: "sheaf of rice", keywords: ["grain"] },
      { emoji: "💐", name: "bouquet", keywords: ["flowers"] },
      { emoji: "🌷", name: "tulip", keywords: ["flower"] },
      { emoji: "🌹", name: "rose", keywords: ["flower", "love"] },
      { emoji: "🥀", name: "wilted", keywords: ["flower", "sad"] },
      { emoji: "🌺", name: "hibiscus", keywords: ["flower"] },
      { emoji: "🌸", name: "cherry blossom", keywords: ["flower", "sakura"] },
      { emoji: "🌼", name: "blossom", keywords: ["flower"] },
      { emoji: "🌻", name: "sunflower", keywords: ["flower"] },
      { emoji: "🌞", name: "sun face", keywords: ["weather"] },
      { emoji: "🌝", name: "full moon face", keywords: ["night"] },
      { emoji: "🌛", name: "first quarter moon", keywords: ["night"] },
      { emoji: "🌜", name: "last quarter moon", keywords: ["night"] },
      { emoji: "🌚", name: "new moon face", keywords: ["night"] },
      { emoji: "🌕", name: "full moon", keywords: ["night"] },
      { emoji: "🌖", name: "waning gibbous", keywords: ["moon"] },
      { emoji: "🌗", name: "last quarter", keywords: ["moon"] },
      { emoji: "🌘", name: "waning crescent", keywords: ["moon"] },
      { emoji: "🌑", name: "new moon", keywords: ["night"] },
      { emoji: "🌒", name: "waxing crescent", keywords: ["moon"] },
      { emoji: "🌓", name: "first quarter", keywords: ["moon"] },
      { emoji: "🌔", name: "waxing gibbous", keywords: ["moon"] },
      { emoji: "🌙", name: "crescent moon", keywords: ["night"] },
      { emoji: "🌎", name: "earth americas", keywords: ["world", "globe"] },
      { emoji: "🌍", name: "earth africa", keywords: ["world", "globe"] },
      { emoji: "🌏", name: "earth asia", keywords: ["world", "globe"] },
      { emoji: "🪐", name: "ringed planet", keywords: ["saturn", "space"] },
      { emoji: "💫", name: "dizzy", keywords: ["star"] },
      { emoji: "⭐", name: "star", keywords: ["favorite"] },
      { emoji: "🌟", name: "glowing star", keywords: ["sparkle"] },
      { emoji: "✨", name: "sparkles", keywords: ["magic", "shine"] },
      { emoji: "⚡", name: "zap", keywords: ["lightning", "fast"] },
      { emoji: "☄️", name: "comet", keywords: ["space"] },
      { emoji: "💥", name: "boom", keywords: ["explosion"] },
      { emoji: "🔥", name: "fire", keywords: ["hot", "lit", "flame"] },
      { emoji: "🌪️", name: "tornado", keywords: ["weather"] },
      { emoji: "🌈", name: "rainbow", keywords: ["pride", "weather"] },
      { emoji: "☀️", name: "sun", keywords: ["weather", "sunny"] },
      { emoji: "🌤️", name: "sun behind small cloud", keywords: ["weather"] },
      { emoji: "⛅", name: "partly cloudy", keywords: ["weather"] },
      { emoji: "🌥️", name: "sun behind large cloud", keywords: ["weather"] },
      { emoji: "☁️", name: "cloud", keywords: ["weather"] },
      { emoji: "🌦️", name: "sun rain", keywords: ["weather"] },
      { emoji: "🌧️", name: "cloud rain", keywords: ["weather"] },
      { emoji: "⛈️", name: "thunder", keywords: ["storm"] },
      { emoji: "🌩️", name: "lightning", keywords: ["storm"] },
      { emoji: "🌨️", name: "snow", keywords: ["weather"] },
      { emoji: "❄️", name: "snowflake", keywords: ["cold", "winter"] },
      { emoji: "☃️", name: "snowman", keywords: ["winter"] },
      { emoji: "⛄", name: "snowman without snow", keywords: ["winter"] },
      { emoji: "🌬️", name: "wind face", keywords: ["blow"] },
      { emoji: "💨", name: "dash", keywords: ["fast", "wind"] },
      { emoji: "💧", name: "droplet", keywords: ["water", "sweat"] },
      { emoji: "💦", name: "sweat droplets", keywords: ["water"] },
      { emoji: "☔", name: "umbrella rain", keywords: ["rain"] },
      { emoji: "☂️", name: "umbrella", keywords: ["rain"] },
      { emoji: "🌊", name: "ocean", keywords: ["wave", "sea"] },
      { emoji: "🌫️", name: "fog", keywords: ["weather"] },
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "🍕",
    items: [
      { emoji: "🍎", name: "red apple", keywords: ["fruit"] },
      { emoji: "🍐", name: "pear", keywords: ["fruit"] },
      { emoji: "🍊", name: "tangerine", keywords: ["orange", "fruit"] },
      { emoji: "🍋", name: "lemon", keywords: ["fruit"] },
      { emoji: "🍌", name: "banana", keywords: ["fruit"] },
      { emoji: "🍉", name: "watermelon", keywords: ["fruit"] },
      { emoji: "🍇", name: "grapes", keywords: ["fruit"] },
      { emoji: "🍓", name: "strawberry", keywords: ["fruit"] },
      { emoji: "🫐", name: "blueberries", keywords: ["fruit"] },
      { emoji: "🍈", name: "melon", keywords: ["fruit"] },
      { emoji: "🍒", name: "cherries", keywords: ["fruit"] },
      { emoji: "🍑", name: "peach", keywords: ["fruit"] },
      { emoji: "🥭", name: "mango", keywords: ["fruit"] },
      { emoji: "🍍", name: "pineapple", keywords: ["fruit"] },
      { emoji: "🥥", name: "coconut", keywords: ["fruit"] },
      { emoji: "🥝", name: "kiwi", keywords: ["fruit"] },
      { emoji: "🍅", name: "tomato", keywords: ["veggie"] },
      { emoji: "🍆", name: "eggplant", keywords: ["veggie"] },
      { emoji: "🥑", name: "avocado", keywords: ["veggie"] },
      { emoji: "🥦", name: "broccoli", keywords: ["veggie"] },
      { emoji: "🥬", name: "leafy green", keywords: ["veggie"] },
      { emoji: "🥒", name: "cucumber", keywords: ["veggie"] },
      { emoji: "🌶️", name: "hot pepper", keywords: ["spicy"] },
      { emoji: "🫑", name: "bell pepper", keywords: ["veggie"] },
      { emoji: "🌽", name: "corn", keywords: ["veggie"] },
      { emoji: "🥕", name: "carrot", keywords: ["veggie"] },
      { emoji: "🫒", name: "olive", keywords: ["veggie"] },
      { emoji: "🧄", name: "garlic", keywords: ["veggie"] },
      { emoji: "🧅", name: "onion", keywords: ["veggie"] },
      { emoji: "🥔", name: "potato", keywords: ["veggie"] },
      { emoji: "🍠", name: "sweet potato", keywords: ["veggie"] },
      { emoji: "🥐", name: "croissant", keywords: ["bread"] },
      { emoji: "🥯", name: "bagel", keywords: ["bread"] },
      { emoji: "🍞", name: "bread", keywords: ["toast"] },
      { emoji: "🥖", name: "baguette", keywords: ["bread"] },
      { emoji: "🫓", name: "flatbread", keywords: ["bread"] },
      { emoji: "🥨", name: "pretzel", keywords: ["snack"] },
      { emoji: "🧀", name: "cheese", keywords: ["dairy"] },
      { emoji: "🥚", name: "egg", keywords: ["breakfast"] },
      { emoji: "🍳", name: "cooking", keywords: ["egg", "fry"] },
      { emoji: "🧈", name: "butter", keywords: ["dairy"] },
      { emoji: "🥞", name: "pancakes", keywords: ["breakfast"] },
      { emoji: "🧇", name: "waffle", keywords: ["breakfast"] },
      { emoji: "🥓", name: "bacon", keywords: ["meat"] },
      { emoji: "🥩", name: "cut of meat", keywords: ["steak"] },
      { emoji: "🍗", name: "poultry leg", keywords: ["chicken"] },
      { emoji: "🍖", name: "meat on bone", keywords: ["meat"] },
      { emoji: "🌭", name: "hot dog", keywords: ["food"] },
      { emoji: "🍔", name: "hamburger", keywords: ["burger"] },
      { emoji: "🍟", name: "fries", keywords: ["chips"] },
      { emoji: "🍕", name: "pizza", keywords: ["food"] },
      { emoji: "🫓", name: "flatbread", keywords: ["food"] },
      { emoji: "🥪", name: "sandwich", keywords: ["food"] },
      { emoji: "🥙", name: "stuffed flatbread", keywords: ["gyro"] },
      { emoji: "🧆", name: "falafel", keywords: ["food"] },
      { emoji: "🌮", name: "taco", keywords: ["mexican"] },
      { emoji: "🌯", name: "burrito", keywords: ["mexican"] },
      { emoji: "🫔", name: "tamale", keywords: ["mexican"] },
      { emoji: "🥗", name: "salad", keywords: ["healthy"] },
      { emoji: "🥘", name: "shallow pan", keywords: ["paella"] },
      { emoji: "🫕", name: "fondue", keywords: ["cheese"] },
      { emoji: "🥫", name: "canned food", keywords: ["can"] },
      { emoji: "🍝", name: "spaghetti", keywords: ["pasta", "italian"] },
      { emoji: "🍜", name: "ramen", keywords: ["noodles", "soup"] },
      { emoji: "🍲", name: "stew", keywords: ["soup"] },
      { emoji: "🍛", name: "curry", keywords: ["rice"] },
      { emoji: "🍣", name: "sushi", keywords: ["japanese"] },
      { emoji: "🍱", name: "bento", keywords: ["japanese"] },
      { emoji: "🥟", name: "dumpling", keywords: ["food"] },
      { emoji: "🦪", name: "oyster", keywords: ["seafood"] },
      { emoji: "🍤", name: "fried shrimp", keywords: ["seafood"] },
      { emoji: "🍙", name: "rice ball", keywords: ["japanese"] },
      { emoji: "🍚", name: "cooked rice", keywords: ["rice"] },
      { emoji: "🍘", name: "rice cracker", keywords: ["snack"] },
      { emoji: "🍥", name: "fish cake", keywords: ["japanese"] },
      { emoji: "🥠", name: "fortune cookie", keywords: ["cookie"] },
      { emoji: "🥮", name: "moon cake", keywords: ["dessert"] },
      { emoji: "🍢", name: "oden", keywords: ["japanese"] },
      { emoji: "🍡", name: "dango", keywords: ["japanese"] },
      { emoji: "🍧", name: "shaved ice", keywords: ["dessert"] },
      { emoji: "🍨", name: "ice cream", keywords: ["dessert"] },
      { emoji: "🍦", name: "soft ice cream", keywords: ["dessert"] },
      { emoji: "🥧", name: "pie", keywords: ["dessert"] },
      { emoji: "🧁", name: "cupcake", keywords: ["dessert"] },
      { emoji: "🍰", name: "shortcake", keywords: ["cake", "dessert"] },
      { emoji: "🎂", name: "birthday cake", keywords: ["party"] },
      { emoji: "🍮", name: "custard", keywords: ["dessert"] },
      { emoji: "🍭", name: "lollipop", keywords: ["candy"] },
      { emoji: "🍬", name: "candy", keywords: ["sweet"] },
      { emoji: "🍫", name: "chocolate", keywords: ["candy"] },
      { emoji: "🍿", name: "popcorn", keywords: ["movie"] },
      { emoji: "🍩", name: "doughnut", keywords: ["donut"] },
      { emoji: "🍪", name: "cookie", keywords: ["dessert"] },
      { emoji: "🌰", name: "chestnut", keywords: ["nut"] },
      { emoji: "🥜", name: "peanuts", keywords: ["nut"] },
      { emoji: "🍯", name: "honey pot", keywords: ["sweet"] },
      { emoji: "🥛", name: "milk", keywords: ["drink"] },
      { emoji: "🍼", name: "baby bottle", keywords: ["milk"] },
      { emoji: "☕", name: "coffee", keywords: ["cafe", "tea"] },
      { emoji: "🍵", name: "tea", keywords: ["green tea"] },
      { emoji: "🧃", name: "juice box", keywords: ["drink"] },
      { emoji: "🥤", name: "cup with straw", keywords: ["soda"] },
      { emoji: "🧋", name: "bubble tea", keywords: ["boba"] },
      { emoji: "🍶", name: "sake", keywords: ["drink"] },
      { emoji: "🍺", name: "beer", keywords: ["drink", "cheers"] },
      { emoji: "🍻", name: "clinking beers", keywords: ["cheers"] },
      { emoji: "🥂", name: "clinking glasses", keywords: ["cheers", "toast"] },
      { emoji: "🍷", name: "wine", keywords: ["drink"] },
      { emoji: "🥃", name: "tumbler", keywords: ["whiskey"] },
      { emoji: "🍸", name: "cocktail", keywords: ["drink"] },
      { emoji: "🍹", name: "tropical drink", keywords: ["cocktail"] },
      { emoji: "🧉", name: "mate", keywords: ["drink"] },
      { emoji: "🍾", name: "champagne", keywords: ["celebrate"] },
      { emoji: "🧊", name: "ice", keywords: ["cold"] },
      { emoji: "🥄", name: "spoon", keywords: ["utensil"] },
      { emoji: "🍴", name: "fork and knife", keywords: ["eat", "dining"] },
      { emoji: "🍽️", name: "plate", keywords: ["dining"] },
      { emoji: "🥣", name: "bowl spoon", keywords: ["cereal"] },
      { emoji: "🥡", name: "takeout", keywords: ["box"] },
      { emoji: "🥢", name: "chopsticks", keywords: ["asian"] },
      { emoji: "🧂", name: "salt", keywords: ["seasoning"] },
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icon: "✈️",
    items: [
      { emoji: "🚗", name: "car", keywords: ["drive"] },
      { emoji: "🚕", name: "taxi", keywords: ["cab"] },
      { emoji: "🚙", name: "suv", keywords: ["car"] },
      { emoji: "🚌", name: "bus", keywords: ["transit"] },
      { emoji: "🚎", name: "trolleybus", keywords: ["transit"] },
      { emoji: "🏎️", name: "race car", keywords: ["fast"] },
      { emoji: "🚓", name: "police car", keywords: ["cop"] },
      { emoji: "🚑", name: "ambulance", keywords: ["emergency"] },
      { emoji: "🚒", name: "fire engine", keywords: ["emergency"] },
      { emoji: "🚐", name: "minibus", keywords: ["van"] },
      { emoji: "🛻", name: "pickup", keywords: ["truck"] },
      { emoji: "🚚", name: "delivery truck", keywords: ["shipping"] },
      { emoji: "🚛", name: "articulated lorry", keywords: ["truck"] },
      { emoji: "🚜", name: "tractor", keywords: ["farm"] },
      { emoji: "🦯", name: "white cane", keywords: ["accessibility"] },
      { emoji: "🦽", name: "manual wheelchair", keywords: ["accessibility"] },
      { emoji: "🦼", name: "motorized wheelchair", keywords: ["accessibility"] },
      { emoji: "🛴", name: "kick scooter", keywords: ["ride"] },
      { emoji: "🚲", name: "bicycle", keywords: ["bike"] },
      { emoji: "🛵", name: "motor scooter", keywords: ["vespa"] },
      { emoji: "🏍️", name: "motorcycle", keywords: ["bike"] },
      { emoji: "🛺", name: "auto rickshaw", keywords: ["tuk tuk"] },
      { emoji: "🚨", name: "revolving light", keywords: ["siren", "alert"] },
      { emoji: "🚔", name: "oncoming police", keywords: ["cop"] },
      { emoji: "🚍", name: "oncoming bus", keywords: ["transit"] },
      { emoji: "🚘", name: "oncoming car", keywords: ["drive"] },
      { emoji: "🚖", name: "oncoming taxi", keywords: ["cab"] },
      { emoji: "🚡", name: "aerial tramway", keywords: ["cable"] },
      { emoji: "🚠", name: "mountain cableway", keywords: ["cable"] },
      { emoji: "🚟", name: "suspension railway", keywords: ["train"] },
      { emoji: "🚃", name: "railway car", keywords: ["train"] },
      { emoji: "🚋", name: "tram car", keywords: ["train"] },
      { emoji: "🚞", name: "mountain railway", keywords: ["train"] },
      { emoji: "🚝", name: "monorail", keywords: ["train"] },
      { emoji: "🚄", name: "bullet train", keywords: ["fast"] },
      { emoji: "🚅", name: "bullet train front", keywords: ["shinkansen"] },
      { emoji: "🚈", name: "light rail", keywords: ["train"] },
      { emoji: "🚂", name: "locomotive", keywords: ["train"] },
      { emoji: "🚆", name: "train", keywords: ["transit"] },
      { emoji: "🚇", name: "metro", keywords: ["subway"] },
      { emoji: "🚊", name: "tram", keywords: ["transit"] },
      { emoji: "🚉", name: "station", keywords: ["train"] },
      { emoji: "✈️", name: "airplane", keywords: ["flight", "travel"] },
      { emoji: "🛫", name: "departure", keywords: ["flight"] },
      { emoji: "🛬", name: "arrival", keywords: ["flight"] },
      { emoji: "🛩️", name: "small airplane", keywords: ["flight"] },
      { emoji: "💺", name: "seat", keywords: ["flight"] },
      { emoji: "🛰️", name: "satellite", keywords: ["space"] },
      { emoji: "🚀", name: "rocket", keywords: ["launch", "space"] },
      { emoji: "🛸", name: "flying saucer", keywords: ["ufo"] },
      { emoji: "🚁", name: "helicopter", keywords: ["chopper"] },
      { emoji: "🛶", name: "canoe", keywords: ["boat"] },
      { emoji: "⛵", name: "sailboat", keywords: ["boat"] },
      { emoji: "🚤", name: "speedboat", keywords: ["boat"] },
      { emoji: "🛥️", name: "motor boat", keywords: ["boat"] },
      { emoji: "🛳️", name: "passenger ship", keywords: ["cruise"] },
      { emoji: "⛴️", name: "ferry", keywords: ["boat"] },
      { emoji: "🚢", name: "ship", keywords: ["cruise"] },
      { emoji: "⚓", name: "anchor", keywords: ["ship"] },
      { emoji: "🪝", name: "hook", keywords: ["tool"] },
      { emoji: "⛽", name: "fuel pump", keywords: ["gas"] },
      { emoji: "🚧", name: "construction", keywords: ["barrier"] },
      { emoji: "🚦", name: "traffic light", keywords: ["signal"] },
      { emoji: "🚥", name: "horizontal traffic light", keywords: ["signal"] },
      { emoji: "🚏", name: "bus stop", keywords: ["transit"] },
      { emoji: "🗺️", name: "world map", keywords: ["travel"] },
      { emoji: "🗿", name: "moai", keywords: ["statue"] },
      { emoji: "🗽", name: "statue of liberty", keywords: ["nyc"] },
      { emoji: "🗼", name: "tokyo tower", keywords: ["japan"] },
      { emoji: "🏰", name: "castle", keywords: ["europe"] },
      { emoji: "🏯", name: "japanese castle", keywords: ["japan"] },
      { emoji: "🏟️", name: "stadium", keywords: ["sports"] },
      { emoji: "🎡", name: "ferris wheel", keywords: ["carnival"] },
      { emoji: "🎢", name: "roller coaster", keywords: ["amusement"] },
      { emoji: "🎠", name: "carousel", keywords: ["horse"] },
      { emoji: "⛲", name: "fountain", keywords: ["park"] },
      { emoji: "⛱️", name: "umbrella beach", keywords: ["vacation"] },
      { emoji: "🏖️", name: "beach", keywords: ["vacation"] },
      { emoji: "🏝️", name: "desert island", keywords: ["vacation"] },
      { emoji: "🏜️", name: "desert", keywords: ["hot"] },
      { emoji: "🌋", name: "volcano", keywords: ["lava"] },
      { emoji: "⛰️", name: "mountain", keywords: ["hike"] },
      { emoji: "🏔️", name: "snow mountain", keywords: ["hike"] },
      { emoji: "🗻", name: "mount fuji", keywords: ["japan"] },
      { emoji: "🏕️", name: "camping", keywords: ["tent"] },
      { emoji: "⛺", name: "tent", keywords: ["camping"] },
      { emoji: "🏠", name: "house", keywords: ["home"] },
      { emoji: "🏡", name: "house garden", keywords: ["home"] },
      { emoji: "🏘️", name: "houses", keywords: ["neighborhood"] },
      { emoji: "🏚️", name: "derelict house", keywords: ["abandoned"] },
      { emoji: "🏗️", name: "building construction", keywords: ["crane"] },
      { emoji: "🏭", name: "factory", keywords: ["industry"] },
      { emoji: "🏢", name: "office", keywords: ["building"] },
      { emoji: "🏬", name: "department store", keywords: ["shopping"] },
      { emoji: "🏣", name: "japanese post office", keywords: ["mail"] },
      { emoji: "🏤", name: "post office", keywords: ["mail"] },
      { emoji: "🏥", name: "hospital", keywords: ["medical"] },
      { emoji: "🏦", name: "bank", keywords: ["money"] },
      { emoji: "🏨", name: "hotel", keywords: ["travel"] },
      { emoji: "🏪", name: "convenience store", keywords: ["shop"] },
      { emoji: "🏫", name: "school", keywords: ["education"] },
      { emoji: "🏩", name: "love hotel", keywords: ["hotel"] },
      { emoji: "💒", name: "wedding", keywords: ["marriage"] },
      { emoji: "⛪", name: "church", keywords: ["religion"] },
      { emoji: "🕌", name: "mosque", keywords: ["religion"] },
      { emoji: "🛕", name: "hindu temple", keywords: ["religion"] },
      { emoji: "🕍", name: "synagogue", keywords: ["religion"] },
      { emoji: "⛩️", name: "shinto shrine", keywords: ["japan"] },
      { emoji: "🕋", name: "kaaba", keywords: ["islam"] },
    ],
  },
  {
    id: "activities",
    label: "Activities",
    icon: "⚽",
    items: [
      { emoji: "⚽", name: "soccer", keywords: ["football", "sport"] },
      { emoji: "🏀", name: "basketball", keywords: ["sport"] },
      { emoji: "🏈", name: "american football", keywords: ["sport"] },
      { emoji: "⚾", name: "baseball", keywords: ["sport"] },
      { emoji: "🥎", name: "softball", keywords: ["sport"] },
      { emoji: "🎾", name: "tennis", keywords: ["sport"] },
      { emoji: "🏐", name: "volleyball", keywords: ["sport"] },
      { emoji: "🏉", name: "rugby", keywords: ["sport"] },
      { emoji: "🥏", name: "flying disc", keywords: ["frisbee"] },
      { emoji: "🎱", name: "8ball", keywords: ["pool", "billiards"] },
      { emoji: "🪀", name: "yo-yo", keywords: ["toy"] },
      { emoji: "🏓", name: "ping pong", keywords: ["table tennis"] },
      { emoji: "🏸", name: "badminton", keywords: ["sport"] },
      { emoji: "🏒", name: "ice hockey", keywords: ["sport"] },
      { emoji: "🏑", name: "field hockey", keywords: ["sport"] },
      { emoji: "🥍", name: "lacrosse", keywords: ["sport"] },
      { emoji: "🏏", name: "cricket", keywords: ["sport"] },
      { emoji: "🪃", name: "boomerang", keywords: ["throw"] },
      { emoji: "🥅", name: "goal net", keywords: ["sport"] },
      { emoji: "⛳", name: "golf", keywords: ["sport"] },
      { emoji: "🪁", name: "kite", keywords: ["fly"] },
      { emoji: "🏹", name: "bow and arrow", keywords: ["archery"] },
      { emoji: "🎣", name: "fishing", keywords: ["rod"] },
      { emoji: "🤿", name: "diving mask", keywords: ["scuba"] },
      { emoji: "🥊", name: "boxing", keywords: ["glove", "fight"] },
      { emoji: "🥋", name: "martial arts", keywords: ["karate"] },
      { emoji: "🎽", name: "running shirt", keywords: ["sport"] },
      { emoji: "🛹", name: "skateboard", keywords: ["skate"] },
      { emoji: "🛼", name: "roller skate", keywords: ["skate"] },
      { emoji: "🛷", name: "sled", keywords: ["winter"] },
      { emoji: "⛸️", name: "ice skate", keywords: ["winter"] },
      { emoji: "🥌", name: "curling", keywords: ["sport"] },
      { emoji: "🎿", name: "skis", keywords: ["winter"] },
      { emoji: "⛷️", name: "skier", keywords: ["winter"] },
      { emoji: "🏂", name: "snowboarder", keywords: ["winter"] },
      { emoji: "🪂", name: "parachute", keywords: ["skydiving"] },
      { emoji: "🏋️", name: "weight lifting", keywords: ["gym"] },
      { emoji: "🤼", name: "wrestling", keywords: ["sport"] },
      { emoji: "🤸", name: "cartwheel", keywords: ["gymnastics"] },
      { emoji: "⛹️", name: "bouncing ball", keywords: ["basketball"] },
      { emoji: "🤺", name: "fencing", keywords: ["sport"] },
      { emoji: "🤾", name: "handball", keywords: ["sport"] },
      { emoji: "🏌️", name: "golfing", keywords: ["sport"] },
      { emoji: "🏇", name: "horse racing", keywords: ["sport"] },
      { emoji: "🧘", name: "lotus", keywords: ["yoga", "meditate"] },
      { emoji: "🏄", name: "surfing", keywords: ["beach"] },
      { emoji: "🏊", name: "swimming", keywords: ["pool"] },
      { emoji: "🤽", name: "water polo", keywords: ["sport"] },
      { emoji: "🚣", name: "rowboat", keywords: ["boat"] },
      { emoji: "🧗", name: "climbing", keywords: ["hike"] },
      { emoji: "🚵", name: "mountain biking", keywords: ["bike"] },
      { emoji: "🚴", name: "biking", keywords: ["bike"] },
      { emoji: "🏆", name: "trophy", keywords: ["win", "award"] },
      { emoji: "🥇", name: "gold medal", keywords: ["first", "win"] },
      { emoji: "🥈", name: "silver medal", keywords: ["second"] },
      { emoji: "🥉", name: "bronze medal", keywords: ["third"] },
      { emoji: "🏅", name: "sports medal", keywords: ["award"] },
      { emoji: "🎖️", name: "military medal", keywords: ["award"] },
      { emoji: "🏵️", name: "rosette", keywords: ["award"] },
      { emoji: "🎗️", name: "reminder ribbon", keywords: ["awareness"] },
      { emoji: "🎫", name: "ticket", keywords: ["event"] },
      { emoji: "🎟️", name: "admission tickets", keywords: ["event"] },
      { emoji: "🎪", name: "circus", keywords: ["tent"] },
      { emoji: "🤹", name: "juggling", keywords: ["circus"] },
      { emoji: "🎭", name: "performing arts", keywords: ["theater", "drama"] },
      { emoji: "🩰", name: "ballet", keywords: ["dance"] },
      { emoji: "🎨", name: "art", keywords: ["paint", "palette"] },
      { emoji: "🎬", name: "clapper", keywords: ["movie", "film"] },
      { emoji: "🎤", name: "microphone", keywords: ["sing", "karaoke"] },
      { emoji: "🎧", name: "headphone", keywords: ["music"] },
      { emoji: "🎼", name: "musical score", keywords: ["music"] },
      { emoji: "🎹", name: "piano", keywords: ["music"] },
      { emoji: "🥁", name: "drum", keywords: ["music"] },
      { emoji: "🪘", name: "long drum", keywords: ["music"] },
      { emoji: "🎷", name: "saxophone", keywords: ["music"] },
      { emoji: "🎺", name: "trumpet", keywords: ["music"] },
      { emoji: "🎸", name: "guitar", keywords: ["music", "rock"] },
      { emoji: "🪕", name: "banjo", keywords: ["music"] },
      { emoji: "🎻", name: "violin", keywords: ["music"] },
      { emoji: "🎲", name: "dice", keywords: ["game", "random"] },
      { emoji: "♟️", name: "chess", keywords: ["game"] },
      { emoji: "🎯", name: "direct hit", keywords: ["target", "bullseye"] },
      { emoji: "🎳", name: "bowling", keywords: ["game"] },
      { emoji: "🎮", name: "video game", keywords: ["controller", "play"] },
      { emoji: "🕹️", name: "joystick", keywords: ["game"] },
      { emoji: "🎰", name: "slot machine", keywords: ["casino"] },
      { emoji: "🧩", name: "puzzle", keywords: ["piece"] },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    items: [
      { emoji: "⌚", name: "watch", keywords: ["time"] },
      { emoji: "📱", name: "mobile phone", keywords: ["iphone", "cell"] },
      { emoji: "📲", name: "phone arrow", keywords: ["call"] },
      { emoji: "💻", name: "laptop", keywords: ["computer", "mac"] },
      { emoji: "⌨️", name: "keyboard", keywords: ["type"] },
      { emoji: "🖥️", name: "desktop", keywords: ["computer"] },
      { emoji: "🖨️", name: "printer", keywords: ["print"] },
      { emoji: "🖱️", name: "mouse", keywords: ["computer"] },
      { emoji: "🖲️", name: "trackball", keywords: ["computer"] },
      { emoji: "🕹️", name: "joystick", keywords: ["game"] },
      { emoji: "🗜️", name: "clamp", keywords: ["tool"] },
      { emoji: "💽", name: "minidisc", keywords: ["disk"] },
      { emoji: "💾", name: "floppy", keywords: ["save", "disk"] },
      { emoji: "💿", name: "cd", keywords: ["disc"] },
      { emoji: "📀", name: "dvd", keywords: ["disc"] },
      { emoji: "📼", name: "vhs", keywords: ["tape"] },
      { emoji: "📷", name: "camera", keywords: ["photo"] },
      { emoji: "📸", name: "camera flash", keywords: ["photo"] },
      { emoji: "📹", name: "video camera", keywords: ["film"] },
      { emoji: "🎥", name: "movie camera", keywords: ["film"] },
      { emoji: "📽️", name: "film projector", keywords: ["movie"] },
      { emoji: "🎞️", name: "film frames", keywords: ["movie"] },
      { emoji: "📞", name: "telephone receiver", keywords: ["call"] },
      { emoji: "☎️", name: "telephone", keywords: ["call"] },
      { emoji: "📟", name: "pager", keywords: ["beeper"] },
      { emoji: "📠", name: "fax", keywords: ["machine"] },
      { emoji: "📺", name: "tv", keywords: ["television"] },
      { emoji: "📻", name: "radio", keywords: ["music"] },
      { emoji: "🎙️", name: "studio mic", keywords: ["podcast"] },
      { emoji: "⏱️", name: "stopwatch", keywords: ["timer"] },
      { emoji: "⏲️", name: "timer clock", keywords: ["timer"] },
      { emoji: "⏰", name: "alarm clock", keywords: ["wake"] },
      { emoji: "🕰️", name: "mantelpiece clock", keywords: ["time"] },
      { emoji: "⌛", name: "hourglass done", keywords: ["time", "wait"] },
      { emoji: "⏳", name: "hourglass", keywords: ["time", "wait"] },
      { emoji: "📡", name: "satellite antenna", keywords: ["signal"] },
      { emoji: "🔋", name: "battery", keywords: ["power"] },
      { emoji: "🔌", name: "electric plug", keywords: ["power"] },
      { emoji: "💡", name: "bulb", keywords: ["idea", "light"] },
      { emoji: "🔦", name: "flashlight", keywords: ["torch"] },
      { emoji: "🕯️", name: "candle", keywords: ["light"] },
      { emoji: "🪔", name: "diya lamp", keywords: ["light"] },
      { emoji: "🧯", name: "fire extinguisher", keywords: ["safety"] },
      { emoji: "🛢️", name: "oil drum", keywords: ["barrel"] },
      { emoji: "💸", name: "money with wings", keywords: ["spend", "cash"] },
      { emoji: "💵", name: "dollar", keywords: ["money", "cash"] },
      { emoji: "💴", name: "yen", keywords: ["money"] },
      { emoji: "💶", name: "euro", keywords: ["money"] },
      { emoji: "💷", name: "pound", keywords: ["money"] },
      { emoji: "🪙", name: "coin", keywords: ["money"] },
      { emoji: "💰", name: "money bag", keywords: ["rich", "cash"] },
      { emoji: "💳", name: "credit card", keywords: ["pay"] },
      { emoji: "💎", name: "gem", keywords: ["diamond", "jewel"] },
      { emoji: "⚖️", name: "balance scale", keywords: ["justice"] },
      { emoji: "🪜", name: "ladder", keywords: ["climb"] },
      { emoji: "🧰", name: "toolbox", keywords: ["tools"] },
      { emoji: "🪛", name: "screwdriver", keywords: ["tool"] },
      { emoji: "🔧", name: "wrench", keywords: ["tool"] },
      { emoji: "🔨", name: "hammer", keywords: ["tool"] },
      { emoji: "⚒️", name: "hammer and pick", keywords: ["tool"] },
      { emoji: "🛠️", name: "hammer and wrench", keywords: ["tool"] },
      { emoji: "⛏️", name: "pick", keywords: ["tool"] },
      { emoji: "🪚", name: "saw", keywords: ["tool"] },
      { emoji: "🔩", name: "nut and bolt", keywords: ["tool"] },
      { emoji: "⚙️", name: "gear", keywords: ["settings"] },
      { emoji: "🪤", name: "mouse trap", keywords: ["trap"] },
      { emoji: "🧱", name: "brick", keywords: ["wall"] },
      { emoji: "⛓️", name: "chains", keywords: ["link"] },
      { emoji: "🧲", name: "magnet", keywords: ["attract"] },
      { emoji: "🔫", name: "water pistol", keywords: ["gun"] },
      { emoji: "💣", name: "bomb", keywords: ["explode"] },
      { emoji: "🧨", name: "firecracker", keywords: ["explosive"] },
      { emoji: "🪓", name: "axe", keywords: ["tool"] },
      { emoji: "🔪", name: "kitchen knife", keywords: ["cook"] },
      { emoji: "🗡️", name: "dagger", keywords: ["weapon"] },
      { emoji: "⚔️", name: "crossed swords", keywords: ["fight"] },
      { emoji: "🛡️", name: "shield", keywords: ["protect"] },
      { emoji: "🚬", name: "cigarette", keywords: ["smoke"] },
      { emoji: "⚰️", name: "coffin", keywords: ["dead"] },
      { emoji: "🪦", name: "headstone", keywords: ["grave"] },
      { emoji: "⚱️", name: "funeral urn", keywords: ["ashes"] },
      { emoji: "🏺", name: "amphora", keywords: ["jar"] },
      { emoji: "🔮", name: "crystal ball", keywords: ["fortune", "magic"] },
      { emoji: "📿", name: "prayer beads", keywords: ["religion"] },
      { emoji: "🧿", name: "nazar", keywords: ["amulet"] },
      { emoji: "💈", name: "barber", keywords: ["pole"] },
      { emoji: "⚗️", name: "alembic", keywords: ["science"] },
      { emoji: "🔭", name: "telescope", keywords: ["space"] },
      { emoji: "🔬", name: "microscope", keywords: ["science"] },
      { emoji: "🕳️", name: "hole", keywords: ["empty"] },
      { emoji: "🩹", name: "bandage", keywords: ["heal"] },
      { emoji: "🩺", name: "stethoscope", keywords: ["doctor"] },
      { emoji: "💊", name: "pill", keywords: ["medicine"] },
      { emoji: "💉", name: "syringe", keywords: ["shot", "vaccine"] },
      { emoji: "🩸", name: "drop of blood", keywords: ["blood"] },
      { emoji: "🧬", name: "dna", keywords: ["science"] },
      { emoji: "🦠", name: "microbe", keywords: ["virus", "germ"] },
      { emoji: "🧫", name: "petri dish", keywords: ["science"] },
      { emoji: "🧪", name: "test tube", keywords: ["science"] },
      { emoji: "🌡️", name: "thermometer", keywords: ["temperature"] },
      { emoji: "🧹", name: "broom", keywords: ["clean"] },
      { emoji: "🪠", name: "plunger", keywords: ["toilet"] },
      { emoji: "🧺", name: "basket", keywords: ["laundry"] },
      { emoji: "🧻", name: "roll of paper", keywords: ["toilet"] },
      { emoji: "🚽", name: "toilet", keywords: ["bathroom"] },
      { emoji: "🚰", name: "potable water", keywords: ["drink"] },
      { emoji: "🚿", name: "shower", keywords: ["bath"] },
      { emoji: "🛁", name: "bathtub", keywords: ["bath"] },
      { emoji: "🛀", name: "person bathing", keywords: ["bath"] },
      { emoji: "🧼", name: "soap", keywords: ["clean"] },
      { emoji: "🪥", name: "toothbrush", keywords: ["dental"] },
      { emoji: "🪒", name: "razor", keywords: ["shave"] },
      { emoji: "🧽", name: "sponge", keywords: ["clean"] },
      { emoji: "🪣", name: "bucket", keywords: ["pail"] },
      { emoji: "🧴", name: "lotion", keywords: ["bottle"] },
      { emoji: "🛎️", name: "bellhop", keywords: ["hotel"] },
      { emoji: "🔑", name: "key", keywords: ["lock"] },
      { emoji: "🗝️", name: "old key", keywords: ["lock"] },
      { emoji: "🚪", name: "door", keywords: ["entrance"] },
      { emoji: "🪑", name: "chair", keywords: ["sit"] },
      { emoji: "🛋️", name: "couch", keywords: ["sofa"] },
      { emoji: "🛏️", name: "bed", keywords: ["sleep"] },
      { emoji: "🛌", name: "person in bed", keywords: ["sleep"] },
      { emoji: "🧸", name: "teddy bear", keywords: ["toy"] },
      { emoji: "🖼️", name: "framed picture", keywords: ["art"] },
      { emoji: "🪞", name: "mirror", keywords: ["reflect"] },
      { emoji: "🪟", name: "window", keywords: ["view"] },
      { emoji: "🛍️", name: "shopping bags", keywords: ["buy"] },
      { emoji: "🛒", name: "shopping cart", keywords: ["buy"] },
      { emoji: "🎁", name: "gift", keywords: ["present", "birthday"] },
      { emoji: "🎈", name: "balloon", keywords: ["party"] },
      { emoji: "🎏", name: "carp streamer", keywords: ["flag"] },
      { emoji: "🎀", name: "ribbon", keywords: ["bow"] },
      { emoji: "🎊", name: "confetti ball", keywords: ["party"] },
      { emoji: "🎉", name: "party popper", keywords: ["celebrate", "tada"] },
      { emoji: "🎎", name: "dolls", keywords: ["japanese"] },
      { emoji: "🏮", name: "red lantern", keywords: ["light"] },
      { emoji: "🎐", name: "wind chime", keywords: ["bell"] },
      { emoji: "🧧", name: "red envelope", keywords: ["luck", "money"] },
      { emoji: "✉️", name: "envelope", keywords: ["mail", "email"] },
      { emoji: "📩", name: "envelope arrow", keywords: ["mail"] },
      { emoji: "📨", name: "incoming envelope", keywords: ["mail"] },
      { emoji: "📧", name: "e-mail", keywords: ["mail"] },
      { emoji: "💌", name: "love letter", keywords: ["mail", "romance"] },
      { emoji: "📥", name: "inbox", keywords: ["tray"] },
      { emoji: "📤", name: "outbox", keywords: ["tray"] },
      { emoji: "📦", name: "package", keywords: ["box", "shipping"] },
      { emoji: "🏷️", name: "label", keywords: ["tag"] },
      { emoji: "🪧", name: "placard", keywords: ["sign"] },
      { emoji: "📪", name: "mailbox closed", keywords: ["mail"] },
      { emoji: "📫", name: "mailbox", keywords: ["mail"] },
      { emoji: "📬", name: "mailbox with mail", keywords: ["mail"] },
      { emoji: "📭", name: "mailbox no mail", keywords: ["mail"] },
      { emoji: "📮", name: "postbox", keywords: ["mail"] },
      { emoji: "📯", name: "postal horn", keywords: ["mail"] },
      { emoji: "📜", name: "scroll", keywords: ["document"] },
      { emoji: "📃", name: "page curl", keywords: ["document"] },
      { emoji: "📄", name: "page facing up", keywords: ["document"] },
      { emoji: "📑", name: "bookmark tabs", keywords: ["tabs"] },
      { emoji: "🧾", name: "receipt", keywords: ["bill"] },
      { emoji: "📊", name: "bar chart", keywords: ["stats", "graph"] },
      { emoji: "📈", name: "chart up", keywords: ["growth", "stocks"] },
      { emoji: "📉", name: "chart down", keywords: ["decline"] },
      { emoji: "🗒️", name: "spiral notepad", keywords: ["notes"] },
      { emoji: "🗓️", name: "spiral calendar", keywords: ["date"] },
      { emoji: "📆", name: "tear-off calendar", keywords: ["date"] },
      { emoji: "📅", name: "calendar", keywords: ["date"] },
      { emoji: "🗑️", name: "wastebasket", keywords: ["trash", "delete"] },
      { emoji: "📇", name: "card index", keywords: ["rolodex"] },
      { emoji: "🗃️", name: "card file box", keywords: ["archive"] },
      { emoji: "🗳️", name: "ballot box", keywords: ["vote"] },
      { emoji: "🗄️", name: "file cabinet", keywords: ["office"] },
      { emoji: "📋", name: "clipboard", keywords: ["notes"] },
      { emoji: "📁", name: "file folder", keywords: ["directory"] },
      { emoji: "📂", name: "open folder", keywords: ["directory"] },
      { emoji: "🗂️", name: "dividers", keywords: ["files"] },
      { emoji: "🗞️", name: "rolled newspaper", keywords: ["news"] },
      { emoji: "📰", name: "newspaper", keywords: ["news"] },
      { emoji: "📓", name: "notebook", keywords: ["notes"] },
      { emoji: "📔", name: "notebook decorative", keywords: ["notes"] },
      { emoji: "📒", name: "ledger", keywords: ["notes"] },
      { emoji: "📕", name: "closed book", keywords: ["read"] },
      { emoji: "📗", name: "green book", keywords: ["read"] },
      { emoji: "📘", name: "blue book", keywords: ["read"] },
      { emoji: "📙", name: "orange book", keywords: ["read"] },
      { emoji: "📚", name: "books", keywords: ["library", "read"] },
      { emoji: "📖", name: "open book", keywords: ["read"] },
      { emoji: "🔖", name: "bookmark", keywords: ["save"] },
      { emoji: "🧷", name: "safety pin", keywords: ["pin"] },
      { emoji: "🔗", name: "link", keywords: ["url", "chain"] },
      { emoji: "📎", name: "paperclip", keywords: ["attach"] },
      { emoji: "🖇️", name: "linked paperclips", keywords: ["attach"] },
      { emoji: "📐", name: "triangular ruler", keywords: ["measure"] },
      { emoji: "📏", name: "straight ruler", keywords: ["measure"] },
      { emoji: "🧮", name: "abacus", keywords: ["math"] },
      { emoji: "📌", name: "pushpin", keywords: ["pin"] },
      { emoji: "📍", name: "round pushpin", keywords: ["location", "map"] },
      { emoji: "✂️", name: "scissors", keywords: ["cut"] },
      { emoji: "🖊️", name: "pen", keywords: ["write"] },
      { emoji: "🖋️", name: "fountain pen", keywords: ["write"] },
      { emoji: "✒️", name: "black nib", keywords: ["write"] },
      { emoji: "🖌️", name: "paintbrush", keywords: ["art"] },
      { emoji: "🖍️", name: "crayon", keywords: ["draw"] },
      { emoji: "📝", name: "memo", keywords: ["note", "write"] },
      { emoji: "✏️", name: "pencil", keywords: ["write"] },
      { emoji: "🔍", name: "magnifying glass left", keywords: ["search", "zoom"] },
      { emoji: "🔎", name: "magnifying glass right", keywords: ["search"] },
      { emoji: "🔏", name: "locked with pen", keywords: ["secure"] },
      { emoji: "🔐", name: "locked with key", keywords: ["secure"] },
      { emoji: "🔒", name: "locked", keywords: ["secure", "private"] },
      { emoji: "🔓", name: "unlocked", keywords: ["open"] },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "✅",
    items: [
      { emoji: "❤️", name: "red heart", keywords: ["love"] },
      { emoji: "🧡", name: "orange heart", keywords: ["love"] },
      { emoji: "💛", name: "yellow heart", keywords: ["love"] },
      { emoji: "💚", name: "green heart", keywords: ["love"] },
      { emoji: "💙", name: "blue heart", keywords: ["love"] },
      { emoji: "💜", name: "purple heart", keywords: ["love"] },
      { emoji: "🖤", name: "black heart", keywords: ["love"] },
      { emoji: "🤍", name: "white heart", keywords: ["love"] },
      { emoji: "🤎", name: "brown heart", keywords: ["love"] },
      { emoji: "💔", name: "broken heart", keywords: ["sad"] },
      { emoji: "❣️", name: "heart exclamation", keywords: ["love"] },
      { emoji: "💕", name: "two hearts", keywords: ["love"] },
      { emoji: "💞", name: "revolving hearts", keywords: ["love"] },
      { emoji: "💓", name: "beating heart", keywords: ["love"] },
      { emoji: "💗", name: "growing heart", keywords: ["love"] },
      { emoji: "💖", name: "sparkling heart", keywords: ["love"] },
      { emoji: "💘", name: "cupid", keywords: ["love"] },
      { emoji: "💝", name: "gift heart", keywords: ["love"] },
      { emoji: "✅", name: "check mark button", keywords: ["done", "yes", "ok"] },
      { emoji: "☑️", name: "check box", keywords: ["done"] },
      { emoji: "✔️", name: "check mark", keywords: ["done", "yes"] },
      { emoji: "❌", name: "cross mark", keywords: ["no", "x", "wrong"] },
      { emoji: "❎", name: "cross mark button", keywords: ["no"] },
      { emoji: "➕", name: "plus", keywords: ["add"] },
      { emoji: "➖", name: "minus", keywords: ["subtract"] },
      { emoji: "➗", name: "divide", keywords: ["math"] },
      { emoji: "✖️", name: "multiply", keywords: ["math"] },
      { emoji: "♾️", name: "infinity", keywords: ["forever"] },
      { emoji: "‼️", name: "double exclamation", keywords: ["bang"] },
      { emoji: "⁉️", name: "exclamation question", keywords: ["huh"] },
      { emoji: "❓", name: "question", keywords: ["help", "?"] },
      { emoji: "❔", name: "white question", keywords: ["help"] },
      { emoji: "❗", name: "exclamation", keywords: ["bang", "!"] },
      { emoji: "❕", name: "white exclamation", keywords: ["bang"] },
      { emoji: "💬", name: "speech balloon", keywords: ["chat", "comment"] },
      { emoji: "👁️‍🗨️", name: "eye in speech bubble", keywords: ["witness"] },
      { emoji: "🗨️", name: "left speech", keywords: ["chat"] },
      { emoji: "🗯️", name: "right anger bubble", keywords: ["mad"] },
      { emoji: "💭", name: "thought balloon", keywords: ["think"] },
      { emoji: "💤", name: "zzz", keywords: ["sleep"] },
      { emoji: "💮", name: "white flower", keywords: ["flower"] },
      { emoji: "🅰️", name: "a button", keywords: ["blood"] },
      { emoji: "🅱️", name: "b button", keywords: ["blood"] },
      { emoji: "🅾️", name: "o button", keywords: ["blood"] },
      { emoji: "🅿️", name: "p button", keywords: ["parking"] },
      { emoji: "🆎", name: "ab button", keywords: ["blood"] },
      { emoji: "🆑", name: "cl button", keywords: ["clear"] },
      { emoji: "🆒", name: "cool button", keywords: ["cool"] },
      { emoji: "🆓", name: "free button", keywords: ["free"] },
      { emoji: "🆔", name: "id button", keywords: ["identity"] },
      { emoji: "🆕", name: "new button", keywords: ["new"] },
      { emoji: "🆖", name: "ng button", keywords: ["no good"] },
      { emoji: "🆗", name: "ok button", keywords: ["ok"] },
      { emoji: "🆘", name: "sos button", keywords: ["help", "emergency"] },
      { emoji: "🆙", name: "up button", keywords: ["up"] },
      { emoji: "🆚", name: "vs button", keywords: ["versus"] },
      { emoji: "🈁", name: "japanese here", keywords: ["here"] },
      { emoji: "🈂️", name: "japanese service", keywords: ["service"] },
      { emoji: "🈷️", name: "japanese monthly", keywords: ["month"] },
      { emoji: "🈶", name: "japanese not free", keywords: ["charge"] },
      { emoji: "🈯", name: "japanese reserved", keywords: ["reserved"] },
      { emoji: "🉐", name: "japanese bargain", keywords: ["deal"] },
      { emoji: "🈹", name: "japanese discount", keywords: ["sale"] },
      { emoji: "🈚", name: "japanese free of charge", keywords: ["free"] },
      { emoji: "🈲", name: "japanese prohibited", keywords: ["forbid"] },
      { emoji: "🉑", name: "japanese acceptable", keywords: ["accept"] },
      { emoji: "🈸", name: "japanese application", keywords: ["apply"] },
      { emoji: "🈴", name: "japanese passing grade", keywords: ["pass"] },
      { emoji: "🈳", name: "japanese vacancy", keywords: ["empty"] },
      { emoji: "㊗️", name: "japanese congratulations", keywords: ["congrats"] },
      { emoji: "㊙️", name: "japanese secret", keywords: ["secret"] },
      { emoji: "🈺", name: "japanese open for business", keywords: ["open"] },
      { emoji: "🈵", name: "japanese no vacancy", keywords: ["full"] },
      { emoji: "🔴", name: "red circle", keywords: ["dot"] },
      { emoji: "🟠", name: "orange circle", keywords: ["dot"] },
      { emoji: "🟡", name: "yellow circle", keywords: ["dot"] },
      { emoji: "🟢", name: "green circle", keywords: ["dot"] },
      { emoji: "🔵", name: "blue circle", keywords: ["dot"] },
      { emoji: "🟣", name: "purple circle", keywords: ["dot"] },
      { emoji: "⚫", name: "black circle", keywords: ["dot"] },
      { emoji: "⚪", name: "white circle", keywords: ["dot"] },
      { emoji: "🟤", name: "brown circle", keywords: ["dot"] },
      { emoji: "🔺", name: "red triangle up", keywords: ["up"] },
      { emoji: "🔻", name: "red triangle down", keywords: ["down"] },
      { emoji: "🔸", name: "orange diamond", keywords: ["small"] },
      { emoji: "🔹", name: "blue diamond", keywords: ["small"] },
      { emoji: "🔶", name: "large orange diamond", keywords: ["diamond"] },
      { emoji: "🔷", name: "large blue diamond", keywords: ["diamond"] },
      { emoji: "🔳", name: "white square button", keywords: ["square"] },
      { emoji: "🔲", name: "black square button", keywords: ["square"] },
      { emoji: "▪️", name: "black small square", keywords: ["square"] },
      { emoji: "▫️", name: "white small square", keywords: ["square"] },
      { emoji: "◾", name: "black medium small square", keywords: ["square"] },
      { emoji: "◽", name: "white medium small square", keywords: ["square"] },
      { emoji: "◼️", name: "black medium square", keywords: ["square"] },
      { emoji: "◻️", name: "white medium square", keywords: ["square"] },
      { emoji: "🟥", name: "red square", keywords: ["square"] },
      { emoji: "🟧", name: "orange square", keywords: ["square"] },
      { emoji: "🟨", name: "yellow square", keywords: ["square"] },
      { emoji: "🟩", name: "green square", keywords: ["square"] },
      { emoji: "🟦", name: "blue square", keywords: ["square"] },
      { emoji: "🟪", name: "purple square", keywords: ["square"] },
      { emoji: "⬛", name: "black large square", keywords: ["square"] },
      { emoji: "⬜", name: "white large square", keywords: ["square"] },
      { emoji: "🟫", name: "brown square", keywords: ["square"] },
      { emoji: "🔈", name: "speaker low", keywords: ["sound"] },
      { emoji: "🔇", name: "muted", keywords: ["mute", "silent"] },
      { emoji: "🔉", name: "speaker medium", keywords: ["sound"] },
      { emoji: "🔊", name: "speaker high", keywords: ["loud"] },
      { emoji: "🔔", name: "bell", keywords: ["notify", "alert"] },
      { emoji: "🔕", name: "bell slash", keywords: ["mute", "quiet"] },
      { emoji: "📣", name: "megaphone", keywords: ["announce"] },
      { emoji: "📢", name: "loudspeaker", keywords: ["announce"] },
      { emoji: "👁‍🗨", name: "eye bubble", keywords: ["witness"] },
      { emoji: "💬", name: "speech", keywords: ["chat"] },
      { emoji: "💭", name: "thought", keywords: ["think"] },
      { emoji: "🃏", name: "joker", keywords: ["cards"] },
      { emoji: "🎴", name: "flower cards", keywords: ["cards"] },
      { emoji: "🀄", name: "mahjong", keywords: ["game"] },
      { emoji: "🕐", name: "one oclock", keywords: ["time"] },
      { emoji: "🕑", name: "two oclock", keywords: ["time"] },
      { emoji: "🕒", name: "three oclock", keywords: ["time"] },
      { emoji: "🕓", name: "four oclock", keywords: ["time"] },
      { emoji: "🕔", name: "five oclock", keywords: ["time"] },
      { emoji: "🕕", name: "six oclock", keywords: ["time"] },
      { emoji: "🕖", name: "seven oclock", keywords: ["time"] },
      { emoji: "🕗", name: "eight oclock", keywords: ["time"] },
      { emoji: "🕘", name: "nine oclock", keywords: ["time"] },
      { emoji: "🕙", name: "ten oclock", keywords: ["time"] },
      { emoji: "🕚", name: "eleven oclock", keywords: ["time"] },
      { emoji: "🕛", name: "twelve oclock", keywords: ["time"] },
      { emoji: "💯", name: "hundred", keywords: ["100", "perfect", "score"] },
      { emoji: "🔠", name: "input latin uppercase", keywords: ["abcd"] },
      { emoji: "🔡", name: "input latin lowercase", keywords: ["abcd"] },
      { emoji: "🔢", name: "input numbers", keywords: ["1234"] },
      { emoji: "🔣", name: "input symbols", keywords: ["symbols"] },
      { emoji: "🔤", name: "input latin letters", keywords: ["abc"] },
      { emoji: "🅰️", name: "a button blood", keywords: ["a"] },
      { emoji: "🆎", name: "ab button blood", keywords: ["ab"] },
      { emoji: "🅱️", name: "b button blood", keywords: ["b"] },
      { emoji: "🆑", name: "cl", keywords: ["clear"] },
      { emoji: "🆒", name: "cool", keywords: ["cool"] },
      { emoji: "🆓", name: "free", keywords: ["free"] },
      { emoji: "ℹ️", name: "information", keywords: ["info"] },
      { emoji: "🆔", name: "id", keywords: ["identity"] },
      { emoji: "Ⓜ️", name: "circled m", keywords: ["metro"] },
      { emoji: "🆕", name: "new", keywords: ["new"] },
      { emoji: "🆖", name: "ng", keywords: ["no good"] },
      { emoji: "🅾️", name: "o button blood", keywords: ["o"] },
      { emoji: "🆗", name: "ok", keywords: ["okay"] },
      { emoji: "🅿️", name: "parking", keywords: ["park"] },
      { emoji: "🆘", name: "sos", keywords: ["help"] },
      { emoji: "🆙", name: "up", keywords: ["update"] },
      { emoji: "🆚", name: "vs", keywords: ["versus"] },
      { emoji: "🈁", name: "here", keywords: ["japanese"] },
      { emoji: "🈂️", name: "service charge", keywords: ["japanese"] },
      { emoji: "🈷️", name: "monthly amount", keywords: ["japanese"] },
      { emoji: "🈶", name: "not free of charge", keywords: ["japanese"] },
      { emoji: "🈯", name: "reserved", keywords: ["japanese"] },
      { emoji: "🉐", name: "bargain", keywords: ["japanese"] },
      { emoji: "🈹", name: "discount", keywords: ["japanese"] },
      { emoji: "🈚", name: "free of charge", keywords: ["japanese"] },
      { emoji: "🈲", name: "prohibited", keywords: ["japanese"] },
      { emoji: "🉑", name: "acceptable", keywords: ["japanese"] },
      { emoji: "🈸", name: "application", keywords: ["japanese"] },
      { emoji: "🈴", name: "passing grade", keywords: ["japanese"] },
      { emoji: "🈳", name: "vacancy", keywords: ["japanese"] },
      { emoji: "㊗️", name: "congratulations", keywords: ["japanese"] },
      { emoji: "㊙️", name: "secret", keywords: ["japanese"] },
      { emoji: "🈺", name: "open for business", keywords: ["japanese"] },
      { emoji: "🈵", name: "no vacancy", keywords: ["japanese"] },
      { emoji: "🔴", name: "red circle", keywords: ["record"] },
      { emoji: "🟠", name: "orange circle", keywords: ["dot"] },
      { emoji: "🟡", name: "yellow circle", keywords: ["dot"] },
      { emoji: "🟢", name: "green circle", keywords: ["dot"] },
      { emoji: "🔵", name: "blue circle", keywords: ["dot"] },
      { emoji: "🟣", name: "purple circle", keywords: ["dot"] },
      { emoji: "🟤", name: "brown circle", keywords: ["dot"] },
      { emoji: "⚫", name: "black circle", keywords: ["dot"] },
      { emoji: "⚪", name: "white circle", keywords: ["dot"] },
      { emoji: "🟥", name: "red square", keywords: ["square"] },
      { emoji: "🟧", name: "orange square", keywords: ["square"] },
      { emoji: "🟨", name: "yellow square", keywords: ["square"] },
      { emoji: "🟩", name: "green square", keywords: ["square"] },
      { emoji: "🟦", name: "blue square", keywords: ["square"] },
      { emoji: "🟪", name: "purple square", keywords: ["square"] },
      { emoji: "🟫", name: "brown square", keywords: ["square"] },
      { emoji: "⬛", name: "black large square", keywords: ["square"] },
      { emoji: "⬜", name: "white large square", keywords: ["square"] },
      { emoji: "◼️", name: "black medium square", keywords: ["square"] },
      { emoji: "◻️", name: "white medium square", keywords: ["square"] },
      { emoji: "◾", name: "black medium-small square", keywords: ["square"] },
      { emoji: "◽", name: "white medium-small square", keywords: ["square"] },
      { emoji: "▪️", name: "black small square", keywords: ["square"] },
      { emoji: "▫️", name: "white small square", keywords: ["square"] },
      { emoji: "🔶", name: "large orange diamond", keywords: ["diamond"] },
      { emoji: "🔷", name: "large blue diamond", keywords: ["diamond"] },
      { emoji: "🔸", name: "small orange diamond", keywords: ["diamond"] },
      { emoji: "🔹", name: "small blue diamond", keywords: ["diamond"] },
      { emoji: "🔺", name: "red triangle pointed up", keywords: ["up"] },
      { emoji: "🔻", name: "red triangle pointed down", keywords: ["down"] },
      { emoji: "💠", name: "diamond with a dot", keywords: ["jewel"] },
      { emoji: "🔘", name: "radio button", keywords: ["circle"] },
      { emoji: "🔳", name: "white square button", keywords: ["button"] },
      { emoji: "🔲", name: "black square button", keywords: ["button"] },
    ],
  },
]

/** Default “quick” row when the user has no recent history yet. */
export const QUICK_EMOJI = [
  "👍",
  "❤️",
  "😂",
  "😮",
  "😢",
  "🎉",
  "👀",
  "✅",
  "🔥",
  "🙏",
] as const

const ALL_ITEMS: EmojiItem[] = (() => {
  const seen = new Set<string>()
  const out: EmojiItem[] = []
  for (const cat of EMOJI_CATEGORIES) {
    for (const item of cat.items) {
      if (seen.has(item.emoji)) continue
      seen.add(item.emoji)
      out.push(item)
    }
  }
  return out
})()

const EMOJI_SET = new Set(ALL_ITEMS.map((i) => i.emoji))

export function isCatalogEmoji(value: string): boolean {
  return EMOJI_SET.has(value)
}

export function getAllEmojiItems(): EmojiItem[] {
  return ALL_ITEMS
}

export function searchEmojiCatalog(query: string): EmojiItem[] {
  const q = query.trim().toLowerCase()
  if (!q) return ALL_ITEMS
  return ALL_ITEMS.filter((item) => {
    if (item.name.includes(q)) return true
    if (item.emoji.includes(q)) return true
    return item.keywords?.some((k) => k.includes(q)) ?? false
  })
}
